In [3]:
import pandas as pd

In [12]:
df1 = pd.read_csv(r'E:\PROJECTWORSHOP\Eggplant Leaf Disease Detection Dataset\csv_data\healthy_leaf\hist_features_healthy_leaf.csv')
df2 = pd.read_csv(r'E:\PROJECTWORSHOP\Eggplant Leaf Disease Detection Dataset\csv_data\insect_Pest_Disease\hist_features_insect_pest_disease.csv')
df3 = pd.read_csv(r'E:\PROJECTWORSHOP\Eggplant Leaf Disease Detection Dataset\csv_data\Leaf_Spot_Disease\hist_features_leaf_spot_disease.csv')
df4 = pd.read_csv(r'E:\PROJECTWORSHOP\Eggplant Leaf Disease Detection Dataset\csv_data\Mosaic_Virus_Disease\hist_features_mosaic_virus_disease.csv')
df5 = pd.read_csv(r'E:\PROJECTWORSHOP\Eggplant Leaf Disease Detection Dataset\csv_data\White_Mold_Disease\hist_features_white_mold_disease.csv')
df6 = pd.read_csv(r'E:\PROJECTWORSHOP\Eggplant Leaf Disease Detection Dataset\csv_data\Wilt_Disease\hist_features_wilt_disease.csv')
df1.shape, df2.shape, df3.shape, df4.shape, df5.shape, df6.shape

((1451, 513), (546, 513), (602, 513), (1362, 513), (63, 513), (65, 513))

In [14]:
df_concat = pd.concat([df1, df2, df3, df4, df5, df6], ignore_index=True)
df_concat.head(), df_concat.shape
df_concat.to_csv('hist_features_disease.csv', index=False)

In [15]:
label_col = 'Name' if 'Name' in df_concat.columns else df_concat.columns[0]

label_counts = df_concat[label_col].value_counts().reset_index()
label_counts.columns = ['label', 'Number of Samples']

label_counts

                  label  Number of Samples
0          healthy_leaf               1451
1  mosaic_virus_disease               1362
2     leaf_spot_disease                602
3   insect_pest_disease                546
4          wilt_disease                 65
5    white_mold_disease                 63

In [16]:
import pandas as pd
file_path = r'E:\PROJECTWORSHOP\Eggplant Leaf Disease Detection Dataset\code_file\efficientnet_feature_extraction\efficientnet_b0_features.csv'
df_rm = pd.read_csv(file_path)
df_rm.head(), df_rm.shape

(                                 image_path    class_name     feature_1  \
 0     Healthy Leaf/Healthy Leaf Image 1.jpg  Healthy Leaf -8.290098e-14
 1    Healthy Leaf/Healthy Leaf Image 10.jpg  Healthy Leaf -6.345624e-14
 2   Healthy Leaf/Healthy Leaf Image 100.jpg  Healthy Leaf -5.153645e-14
 3  Healthy Leaf/Healthy Leaf Image 1000.jpg  Healthy Leaf -4.892110e-14
 4  Healthy Leaf/Healthy Leaf Image 1001.jpg  Healthy Leaf -9.685673e-14

       feature_2     feature_3     feature_4     feature_5     feature_6  \
 0  1.859740e-14 -5.178059e-14 -1.061762e-13 -1.337465e-14 -3.808357e-14
 1  2.451680e-14 -3.956058e-14 -8.721216e-14 -3.064124e-14 -1.899945e-14
 2  1.297021e-14 -2.795746e-14 -8.813483e-14 -3.660275e-14 -2.421464e-14
 3  1.549814e-14 -3.585943e-14 -5.824281e-14 -1.486701e-14 -1.787997e-14
 4  3.583746e-14 -6.679727e-14 -6.728174e-14 -1.309322e-14 -5.041380e-14

       feature_7     feature_8  ...  feature_1271  feature_1272  feature_1273  \
 0  5.101926e-14  3.414337e-15  ...  1.590617e-14 -1.023627e-13 -9.511013e-14
 1  4.209355e-14  1.858092e-15  ... -2.514691e-14 -7.081281e-14 -6.569402e-14
 2  5.681673e-14 -1.293907e-15  ... -8.647973e-15 -7.760024e-14 -5.212022e-14
 3  5.063044e-14 -2.272379e-14  ... -3.869157e-15 -5.555661e-14 -7.292960e-14
 4  2.980424e-14 -2.582132e-14  ... -1.534075e-14 -9.531376e-14 -1.235505e-13

    feature_1274  feature_1275  feature_1276  feature_1277  feature_1278  \
 0 -1.369116e-13  6.964526e-14  4.150935e-14 -1.383390e-14  2.597234e-14
 1 -1.003852e-13  4.930166e-14  3.503730e-14 -1.661171e-14  5.195892e-15
 2 -1.075963e-13  3.105589e-14  3.853976e-14 -1.901202e-14  2.633487e-14
 3 -9.015457e-14  5.680112e-14  6.223250e-14 -1.574104e-14 -7.290928e-15
 4 -1.230243e-13  8.573608e-14  6.025996e-14  9.747192e-15 -1.885420e-14

    feature_1279  feature_1280
 0 -8.194685e-14 -5.254769e-14
 1 -4.051387e-14 -1.947737e-14
 2 -3.702785e-14 -2.750258e-14
 3 -5.089620e-14 -1.996072e-14
 4 -8.679131e-14 -3.169670e-14

 [5 rows x 1282 columns],
 (4089, 1282))

In [17]:
df_new = df_rm.iloc[:, 1:]
df_new.shape

(4089, 1281)

In [18]:
label_col = 'label' if 'label' in df_new.columns else df_new.columns[0]

label_counts = df_new[label_col].value_counts().reset_index()
label_counts.columns = ['label', 'Number of Samples']

label_counts

                  label  Number of Samples
0          Healthy Leaf               1451
1  Mosaic_Virus_Disease               1362
2     Leaf_Spot_Disease                602
3   Insect_Pest_Disease                546
4          Wilt_Disease                 65
5    White_Mold_Disease                 63

In [19]:
df_new.to_csv(r'csv_deeplearning_features\efficientnetb0_features.csv', index=False)

In [6]:
df_hist = pd.read_csv(r"E:\PROJECTWORSHOP\Eggplant Leaf Disease Detection Dataset\csv_data\hist_features_all_disease.csv")
df_basic = pd.read_csv(r"E:\PROJECTWORSHOP\Eggplant Leaf Disease Detection Dataset\csv_data\basic_features_all_diseases.csv")
df_hist.shape, df_basic.shape

((4089, 513), (4089, 19))

In [7]:
df_basic = df_basic.iloc[:, 1:]
df_basic.shape

(4089, 18)

In [ ]:
df_merge = pd.concat([df_hist, df_basic], ignore_index=True, axis=1)
df_merge.shape

(4089, 531)

In [12]:
df_merge.to_csv('hist_basic_all_disease.csv', index=False)